modLoader = "javafml"
loaderVersion = "[4,)"

license = "Apache-2.0"

[[mods]]
modId = "serverspulse"
version = "${version}"
displayName = "ServersPulse"
description = "Server monitoring agent for ServersPulse"
authors = "bwmp"
displayURL = "https://serverspulse.com"

[[dependencies.serverspulse]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,27)"
ordering = "NONE"
side = "SERVER"

[[dependencies.serverspulse]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,27)"
ordering = "NONE"
side = "SERVER"
