modLoader = "javafml"
loaderVersion = "[40,52)"

license = "Apache-2.0"

[[mods]]
modId = "serverspulse"
version = "${version}"
displayName = "ServersPulse"
description = "Server monitoring agent for ServersPulse"
authors = "bwmp"
displayURL = "https://serverspulse.com"

[[dependencies.serverspulse]]
modId = "forge"
mandatory = true
versionRange = "[40,52)"
ordering = "NONE"
side = "SERVER"

[[dependencies.serverspulse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.21.1)"
ordering = "NONE"
side = "SERVER"
